#!/bin/sh
# madai_catenate_traces
if [ -z "$1" ] ; then
  echo "Usage:" >&2;
  echo " $0 FILE [MORE_FILES ...] > OUTFILE" >&2;
  echo "" >&2;
  echo "Remove the first line of all but the first file and concatenate" >&2;
  echo "them together. Prints to standard output." >&2;
  echo "" >&2;
  exit 1;
fi
# The first cat forces the filename to be exact, zcat would otherwise add gz
# The -f option on zcat makes it pass through uncompressed files
cat "$1" | zcat -f
shift
for arg; do
  cat "$arg" | zcat -f | tail -n+2
done
